server:
  port: 8123
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: LearningManage

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
