ARG NGINX_IMAGE
FROM ${NGINX_IMAGE}

ARG FRONTEND_SHA
LABEL org.opencontainers.image.revision=${FRONTEND_SHA}
LABEL org.opencontainers.image.source="https://github.com/Zhi-Hua-Yuan/learning-manage-frontend"

COPY deploy/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY frontend/dist/ /usr/share/nginx/html/

EXPOSE 80
